### ISSUE TITLE
Question in running tutorials

### ISSUE THREAD

**Issue by LzYzL** [PettingZoo-Team/SuperSuit#100]
**I download pettingzoo files and unzip them on the desktop.The operating system is win10 and the library versions are below.**

_Requirement already satisfied: pettingzoo>=1.6.0 in c:\users\lzyzl\appdata\local\programs\python\python37\lib\site-packages (from supersuit) (1.11.0)
Requirement already satisfied: cloudpickle in c:\users\lzyzl\appdata\local\programs\python\python37\lib\site-packages (from supersuit) (1.6.0)
Requirement already satisfied: opencv-python~=3.4.0 in c:\users\lzyzl\appdata\local\programs\python\python37\lib\site-packages (from supersuit) (3.4.15.55)
Requirement already satisfied: numpy>=1.18.0 in c:\users\lzyzl\appdata\local\programs\python\python37\lib\site-packages (from pettingzoo>=1.6.0->supersuit) (1.19.5)
Requirement already satisfied: gym>=0.18.0 in c:\users\lzyzl\appdata\local\programs\python\python37\lib\site-packages (from pettingzoo>=1.6.0->supersuit) (0.18.3)
Requirement already satisfied: Pillow<=8.2.0 in c:\users\lzyzl\appdata\local\programs\python\python37\lib\site-packages (from gym>=0.18.0->pettingzoo>=1.6.0->supersuit) (8.2.0)
Requirement already satisfied: pyglet<=1.5.15,>=1.4.0 in c:\users\lzyzl\appdata\local\programs\python\python37\lib\site-packages (from gym>=0.18.0->pettingzoo>=1.6.0->supersuit) (1.5.15)
Requirement already satisfied: scipy in c:\users\lzyzl\appdata\local\programs\python\python37\lib\site-packages (from gym>=0.18.0->pettingzoo>=1.6.0->supersuit) (1.7.1)
Installing collected packages: supersuit
Successfully installed supersuit-3.0.1_

**When I tried to run 13_lines.py in tutorials an AttributeError occured that "AttributeError: 'SharedArray' object has no attribute 'dtype'".**
_Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\lzyzl\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\lzyzl\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\lzyzl\AppData\Local\Programs\Python\Python37\lib\site-packages\supersuit\vector\utils\shared_array.py", line 20, in __setstate__
    self._set_np_arr()
  File "C:\Users\lzyzl\AppData\Local\Programs\Python\Python37\lib\site-packages\supersuit\vector\utils\shared_array.py", line 13, in _set_np_arr
    self.np_arr = np.frombuffer(self.shared_arr, dtype=self.dtype).reshape(self.shape)
AttributeError: 'SharedArray' object has no attribute 'dtype'_

**I will sincerely appreciate your help.**

**Comment by benblack769** [comment]
Supersuit does not have support for windows. In particular, the multiprocessing feature of the supersuit.concat_vec_envs_v0() wrapper has known issues with windows (for example, see #75) which we are not intending to fix. If you want to make this work, I recommend trying to turn off multiprocessing by setting the `num_cpus` argument of supersuit to 1.

```
env_single = ss.concat_vec_envs_v0(env_single, 8, num_cpus=1, base_class='stable_baselines3')
```

However, if additional issues occur, we might not be able to help, because again, windows is hard to support, and it is not standard to support windows due to these innumerable difficulties writing software for the platform, and so we don't officially support it. I recommend installing the windows subsystem for linux here: https://ubuntu.com/tutorials/ubuntu-on-windows#1-overview. This will make your life so much easier. It is what I use on a daily basis to develop this software.

Hope this helps.

**Comment by jkterry1** [comment]
Hey, I'm going to close this due to inactivity
