### ISSUE TITLE
ModuleNotFoundError: No module named 'gym' (and other dependency problems)

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/SuperSuit#21]
It looks like there is no dependency for gym, pettingzoo, and lycon given in `setup.py`. This leads to an installation error. To reproduce using a conda environment to ensure an existing gym installation does not masks this problem:

```
conda create -n test_supersuit python=3.8
conda activate test_supersuit
pip install supersuit
```
Returns the error: `ModuleNotFoundError: No module named 'gym'` This can be fixed locally by running `pip install gym`, but it should be fixed in `setup.py` to ease the entire installation process. A similar problem then arises for `pettingzoo` and `lycon`. 

It might be easy to dismiss this problem due to the fact that I imagine that supersuit is only ever expected to be installed on a system that already has `pettingzoo` installed; however, if you use a conda environment file to get an isolated environment to work on, you aren't guaranteed to have pettingzoo install prior to supersuit and thus the error will arise

**Comment by justinkterry** [comment]
We'll look into this more, but setup.py does have `install_requires=["pettingzoo>=0.1.14", "lycon"]`, and pettingzoo requires Gym, so that's a bit odd.

As an aside, people can use SuperSuit for Gym and not PettingZoo environments, so we don't inherently need to assume they have PettingZoo installed. It's just that PettingZoo without any extras is tiny, so it's easier to just keep it as a dependency for all installs.

**Comment by weepingwillowben** [comment]
Sorry, I see this error now. This is some stupid error I introduced a few days ago. I'll fix it, and make sure CI testing catches it next time.

**Comment by weepingwillowben** [comment]
This should be fixed now and released. Thanks for bringing up this important issue.
