### ISSUE TITLE
Self-play environment modification

### ISSUE THREAD

**Issue by dotaking2021** [PettingZoo-Team/SuperSuit#64]
Hello

I am interested in formulating Pong to a self-play environment. 

I am following your tutorial here: 

```
from pettingzoo.atari import pong_v0
import supersuit as ss
env = pistonball_v4.parallel_env()
env = ss.color_reduction_v0(env, mode='B')
env = ss.resize_v0(env, x_size=84, y_size=84)
env = ss.frame_stack_v1(env, 3)
env = ss.pettingzoo_env_to_vec_env_v0(env)
env = ss.concat_vec_envs_v0(env, 8, num_cpus=4, base_class='stable_baselines3')
model = PPO('CnnPolicy', env, verbose=3, n_steps=16)
```

If I want to modify this to be self-play, do I need to change `concat_vec_envs_v0 `?

**Comment by weepingwillowben** [comment]
Hi, I'm glad you would like to extend our tutorial code to work in the Atari environments.

If you use the above code snippet for pong_v1, the result will be a self-play. So there is no need to change anything to make it self-play. The reason is because the `pettingzoo_env_to_vec_env_v0` stacks the agents along the environment dimention. I.e. it lays out the agents and pretends they are environments like so:

```
env_1_first_0
env_1_second_0
env_2_first_0
env_2_second_0
```

Since stable baselines treats the sub-environments in the vector environments as identical, parallel environments, it executes the same policy for each agent, and trains them on the same data, leading to self-play.

Now, there is a problem with this model that is specific to Atari. In most multi-agent games, the observations between the two players differ, allowing the agent to know which of the two roles they are playing. However, in Atari, both players look at the same screen. So they don't know if they are playing the first or second player at all!

We have a wrapper specifically designed to handle this issue, the `agent_indicator_v0` wrapper. This wrapper adds another two channels to the image, and the first channel is set to one if you are playing as player 1 and the second is set if you are playing player 2. This way, the observation contains information about which role you play. While this strategy is somewhat naive, and there are probably better ones, such as rotating or inverting the image, it seems to work well enough for pong.

You may also want to change the preprocessing wrappers to match those in the Atari documentation [here](https://www.pettingzoo.ml/atari#preprocessing). That documentation matches the functionality of OpenAI baseline's wrappers for the Atari environments, to the degree possible.

P.S. PettingZoo and SuperSuit have the same maintainers. There is no reason to post an issue on both.

**Comment by dotaking2021** [comment]
Thanks for the reply! Can I not load a policy that's fixed throughout and play 'second_0' only?

In that case, do you know how should I modified the enviornment?

**Comment by weepingwillowben** [comment]
Sure. You can see an example of loading the policy and playing here https://github.com/PettingZoo-Team/PettingZoo/blob/master/tutorials/13_lines.py

Doing it this way allows you to use a trained policy with a specific agent.

**Comment by justinkterry** [comment]
Hey, I'm goingo to close this issue but if you need anything else please let me know.

**Comment by dotaking2021** [comment]
Hello

One more question. 
If I use 
`pettingzoo_env_to_vec_env_v0`, I get:
```
env_1_first_0
env_1_second_0
env_2_first_0
env_2_second_0
```

However, if I don't want to do this, I want to have two separate agents, each agent receive separate action like this:

```
env_1_first_0
env_2_first_0
```
Then in this case, how do I have 
`env.step(first_0); 
env.step(second_0); 
obs, reward, done, info = env.last()
`

In this setup, how do I do it with the `ss.pettingzoo_env_to_vec_env_v0` only ?

**Comment by dotaking2021** [comment]
@weepingwillowben @justinkterry

**Comment by weepingwillowben** [comment]
So you can't do it with the pettingzoo_env_to_vec_env_v0 

What you want seems to be the vectorize_aec_env_v0, which creates a different sort of vector environment based on the AEC model. It does get a bit complicated though in order to handle agent death, so please look at the documentation here: https://github.com/PettingZoo-Team/SuperSuit/blob/master/supersuit/aec_vector/base_aec_vec_env.py#L10 and ask if you have any questions.

Note that this function takes in a PettingZoo AEC env instead of a parallel env.
